from item import Item
from catalog import Catalog
item1 = Item("Green Book", "Biography")
print(item1)
item2 = Item("The God", "Crime")
print(item2)
item2.set_name("The Godfather")
print(item2)
item3 = Item("Schindler's List", "Biography")
print(item3)
item3.set_category("Drama")
print(item3)
catalog = Catalog("Films")
catalog.add(item1)
catalog.add(item2)
catalog.add(item3)
print(catalog)
catalog.remove(item2)
print(catalog)
catalog.set_name("Favorite Movies")
print(catalog)
catalog.clear()
print(catalog)
catalog.clear()
catalog.set_name("Best Movies Ever")
print(catalog)